# Generated by Django 5.0.7 on 2024-07-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]


operations = [
    migrations.CreateModel(
        name='CarModel',
        fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('brand', models.CharField(max_length=100)),
            ('price', models.IntegerField()),
            ('year', models.IntegerField()),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('updated_at', models.DateTimeField(auto_now=True)),
        ],
        options={
            'db_table': 'cars',
        },
    ),
]
